---
# Role tasks

- block:
    - name: Configure xinetd service
      template:
        src: service.j2
        dest: >-
          {{ xinetd_xinetd_d_path }}/{{ xinetd_service_id
                                        | default(xinetd_service_name) }}
        owner: root
        group: root
        mode: 0644
        backup: yes
      register: xinetd_service_configure_result

    - name: Reload xinetd
      service:
        name: xinetd
        state: reloaded
      when: xinetd_service_configure_result is changed
  tags:
    - role::xinetd_service
