---
# Role tasks

- name: install xinetd service
  import_tasks: install.yml
  tags:
    - role::xinetd_service
    - role::xinetd_service::install

- name: configure xinetd service
  import_tasks: configure.yml
  tags:
    - role::xinetd_service
    - role::xinetd_service::configure
