---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  export ANSIBLE_ACTION_PLUGINS=$PWD/action_plugins
  export ANSIBLE_BECOME_PLUGINS=$PWD/become_plugins
  export ANSIBLE_CACHE_PLUGINS=$PWD/cache_plugins
  export ANSIBLE_CALLBACK_PLUGINS=$PWD/callback_plugins
  export ANSIBLE_CLICONF_PLUGINS=$PWD/cliconf_plugins
  export ANSIBLE_CONNECTION_PLUGINS=$PWD/connection_plugins
  export ANSIBLE_DOC_FRAGMENT_PLUGINS=$PWD/doc_fragment_plugins
  export ANSIBLE_FILTER_PLUGINS=$PWD/filter_plugins
  export ANSIBLE_HTTPAPI_PLUGINS=$PWD/httpapi_plugins
  export ANSIBLE_INVENTORY_PLUGINS=$PWD/inventory_plugins
  export ANSIBLE_LIBRARY=$PWD/library
  export ANSIBLE_LOOKUP_PLUGINS=$PWD/lookup_plugins
  export ANSIBLE_NETCONF_PLUGINS=$PWD/netconf_plugins
  export ANSIBLE_STRATEGY_PLUGINS=$PWD/strategy_plugins
  export ANSIBLE_TERMINAL_PLUGINS=$PWD/terminal_plugins
  export ANSIBLE_TEST_PLUGINS=$PWD/test_plugins
  export ANSIBLE_VARS_PLUGINS=$PWD/vars_plugins
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: centos:6
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
  - name: "fedora29-${INSTANCE_UUID:-1}"
    image: fedora:29
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
  - name: "fedora30-${INSTANCE_UUID:-1}"
    image: fedora:30
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
provisioner:
  name: ansible
  inventory:
    hosts:
      molecule_hosts:
        vars:
          xinetd_service_name: echo
          xinetd_service_id: echo-stream
          xinetd_service_type: INTERNAL
          xinetd_service_disable: no
          xinetd_service_socket_type: stream
          xinetd_service_protocol: tcp
          xinetd_service_user: root
          xinetd_service_wait: "no"
          xinetd_service_only_from: [ 127.0.0.1 ]
          xinetd_service_no_access: [ 127.0.0.5 ]
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
