---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check echo service is listening
      wait_for:
        host: localhost
        state: started
        port: 7
        delay: 5
        timeout: 10
      changed_when: false

    - name: Check tcp wrappers allow file
      command: "grep 'echo-stream:127.0.0.1' /etc/hosts.allow"
      args:
        warn: no
      register: check_tcp_wrappers_allow_result
      changed_when: false
      failed_when: check_tcp_wrappers_allow_result.rc != 0

    - name: Check tcp wrappers deny file
      command: "grep 'echo-stream:127.0.0.5' /etc/hosts.deny"
      args:
        warn: no
      register: check_tcp_wrappers_deny_result
      changed_when: false
      failed_when: check_tcp_wrappers_deny_result.rc != 0
